### PR TITLE
React Project - Calculator - Milestone 1

### PR DESCRIPTION
**Pull request by macnick**
This is milestone-1 of the React Calculator project. 

In this milestone I did the following:
- Initialized a new react app using create-react-app
- Added  `prop-types` and `big.js` using npm
- Run with `npm start` to make sure the app runs correctly
- Followed the instructions in `create-react-app-buildpack` to deploy the app to Heroku 
  - Initialized a git repo
  - Created a Heroku app
  - Commited and deployed to Heroku

Please review my code.

Nick

### CODE REVIEW

**Review by shloch — CHANGES_REQUESTED** [review]
## Hello @macnick , 

README is part of the setup....please edit it with relevant information (the usual suspects)

- author name
- project name
- project description
 etc

**Comment by macnick** [comment]
Hi Shey,

OK, I thought I should do it later. Fixing it now.

Thank you,

Nick

**Comment by macnick** [comment]
Fixed a full README.

Please review my code.

Nick

**Review by shloch — APPROVED** [review]
### Good to go
accomplished

Happy coding

**Comment by macnick** [comment]
Thank you so much, Shey.

**Pull request merged**
